name: flutter_appc
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.5.3

  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4
  firebase_analytics: ^6.3.0
  
#  flutter_login_facebook: 0.4.0+1
  rxdart: ^0.24.1
  font_awesome_flutter: ^8.11.0
  flutter_appavailability: ^0.0.21
  url_launcher: ^5.7.10
  intl: ^0.16.1
  provider: ^4.3.2+3
  http: ^0.12.2
  google_sign_in: ^4.5.6

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/01.jpg
    - assets/logo.PNG
    - assets/google-logo.png
    - assets/facebook-logo.png
  fonts:
    - family: Sarabun
      fonts:
        - asset: fonts/Sarabun-Regular.ttf
          weight: 300